(() => {
  const dom = {
    canvas: document.getElementById('whiteboard-canvas'),
    objectLayer: document.getElementById('object-layer'),
    toolButtons: [...document.querySelectorAll('.toolsbar .tool')],
    optionPanels: [...document.querySelectorAll('.options')],
    optionButtons: [...document.querySelectorAll('.options .option')],
    dialogBackdrop: document.getElementById('dialog-backdrop'),
    inputDialog: document.getElementById('input-dialog'),
    dialogTitle: document.getElementById('dialog-title'),
    dialogLabel: document.getElementById('dialog-label'),
    dialogInput: document.getElementById('dialog-input'),
    dialogCancel: document.getElementById('dialog-cancel'),
    dialogClose: document.getElementById('dialog-close'),
    confirmBackdrop: document.getElementById('confirm-backdrop'),
    confirmTitle: document.getElementById('confirm-title'),
    confirmMessage: document.getElementById('confirm-message'),
    confirmCancel: document.getElementById('confirm-cancel'),
    confirmClose: document.getElementById('confirm-close'),
    confirmSubmit: document.getElementById('confirm-submit'),
    controlPopover: document.getElementById('control-popover'),
    controlTitle: document.getElementById('control-title'),
    controlClose: document.getElementById('control-close'),
    controlRangeRow: document.getElementById('control-range-row'),
    controlRange: document.getElementById('control-range'),
    controlValue: document.getElementById('control-value'),
    colorPopover: document.getElementById('color-popover'),
    colorClose: document.getElementById('color-close'),
    colorInput: document.getElementById('color-input'),
    colorPreview: document.getElementById('color-preview'),
    colorPreviewSwatch: document.getElementById('color-preview-swatch'),
    colorValue: document.getElementById('color-value'),
    colorPipette: document.getElementById('color-pipette'),
    colorToolSwatch: document.getElementById('color-tool-swatch'),
    layerPopover: document.getElementById('layer-popover'),
    layerClose: document.getElementById('layer-close'),
    layerList: document.getElementById('layer-list'),
    toast: document.getElementById('toast')
  };

  const ctx = dom.canvas.getContext('2d');

  const state = {
    activeTool: 'select',
    activePanel: 'wall',
    drawMode: 'pencil',
    lineStyle: 'straight',
    shapeType: 'rectangle',
    color: '#111827',
    lineWidth: 4,
    opacity: 1,
    eraserSize: 18,
    eraseMode: 'objects',
    layerFilter: 'notes',
    isPointerActive: false,
    pointerId: null,
    pointerStart: null,
    currentPoints: [],
    history: [],
    historyIndex: -1,
    selectedObject: null,
    dragState: null,
    transformMode: null,
    dialogResolver: null,
    confirmResolver: null,
    controlUpdate: null,
    toastTimer: null,
    objectCounter: 0,
    drawingCounter: 0,
    drawings: [],
    loaded: false,
    canvasCssWidth: 0,
    canvasCssHeight: 0,
    pixelRatio: 1,
    saveTimer: null,
    restoring: false,
    dirty: false,
    eraseChanged: false,
    lastErasePoint: null,
    controlChanged: false,
    controlRecordHistory: false
  };

  window.LCWhiteboard = { dom, ctx, state };
})();
